language: python
python: "3.7"
install:
    - pip install tox-travis
    - pip install -r requirements.txt
matrix:
  include:
    - python: 37
      env:
       - TOX_ENV=py37
    - python: 36
      env:
        - TOX_ENV=py36
    - python: 35
      env:
        - TOX_ENV=py35
script:
    - flask run &
    - tox
