language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
services:
  - redis
env:
  - FLASK=1.1.0
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
script:
  - tox